/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/aFvlAnKPhUa
 */
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Textarea } from "@/components/ui/textarea"
import { Select } from "@/components/ui/select"
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <Card className="w-full max-w-lg mx-auto">
      <CardHeader>
        <CardTitle>Submit your blog post</CardTitle>
        <CardDescription>Fill out the form below to submit your blog post.</CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        <div className="space-y-2">
          <Label htmlFor="title">Title</Label>
          <Input id="title" placeholder="Enter the title" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="content">Content</Label>
          <Textarea className="min-h-[100px]" id="content" placeholder="Enter the content" required />
        </div>
        <div className="space-y-2">
          <Label htmlFor="image">Image</Label>
          <Input accept="image/*" id="image" type="file" />
        </div>
        <div className="space-y-2">
          <Label htmlFor="state">State</Label>
          <Select defaultValue="0" id="state">
            <option disabled value="0">
              Select a state
            </option>
            <option value="1">California</option>
            <option value="2">New York</option>
            <option value="3">Texas</option>
            <option value="4">Florida</option>
          </Select>
        </div>
        <div className="space-y-2">
          <Label htmlFor="district">District</Label>
          <Select defaultValue="0" id="district">
            <option disabled value="0">
              Select a district
            </option>
            <option value="1">1st</option>
            <option value="2">2nd</option>
            <option value="3">3rd</option>
            <option value="4">4th</option>
          </Select>
        </div>
      </CardContent>
      <CardFooter>
        <Button size="sm">Submit</Button>
      </CardFooter>
    </Card>
  )
}
